### ISSUE TITLE
Error when using Kubernetes Secrets

### ISSUE THREAD

**Issue by eduardobaitello** [qnib/init-plain#1]
I'm trying to use the `qnib/plain-kafka-manager:2018-04-25` image to deploy kafka-manager in a Kubernetes Cluster.

When container starts, the `/opt/entry/10-docker-secrets.env` init-plain script exits with a error:
```
[II] qnib/init-plain script v0.4.28
> execute entrypoint '/opt/entry/00-logging.sh'
> execute entrypoint '/opt/entry/10-docker-secrets.env'
[II] Set environment variable KUBERNETES.IO from '/run/secrets/kubernetes.io'
cat: read error: Is a directory
/opt/entry/10-docker-secrets.env: line 9: declare: `KUBERNETES.IO=': not a valid identifier
```

The problem is that Kubernetes have a structure with subdirs in `/run/secrets/` directory:
```
root@my-kubernetes-container:/run/secrets# pwd
/run/secrets

root@my-kubernetes-container:/run/secrets# tree
.
└── kubernetes.io
    └── serviceaccount
        ├── ca.crt -> ..data/ca.crt
        ├── namespace -> ..data/namespace
        └── token -> ..data/token

2 directories, 3 files
```

Maybe the init-plain scripts can be improved to work also on Kubernetes :)

**Comment by ChristianKniep** [comment]
Sure can. :)
I am almost on my way to DockerCon and have to prepare my talk. 
Please ping me if no process occurs here - I'll try to float it in my backlog.

**Comment by cameronbraid** [comment]
I'm getting the same error

**Comment by ChristianKniep** [comment]
I created a new image with init-plain v0.4.32, which should be kafka-ready...  `qnib/plain-kafka-manager:1.3.3.18-1`

Haven't tried it myself due to time constraints. Please check the new image and provide feedback.
